name: Setup Windows Runner from Repo

on:
  workflow_dispatch:

jobs:
  setup-windows:
    runs-on: windows-latest
    steps:
      - name: Install Python 3.10
        shell: pwsh
        run: |
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.10.11/python-3.10.11-amd64.exe" -OutFile "$env:TEMP\python-installer.exe"
          Start-Process -FilePath "$env:TEMP\python-installer.exe" -ArgumentList "/quiet InstallAllUsers=1 PrependPath=1" -Wait
          Write-Host "Python version:"
          python --version

      - name: Download & Launch RustDesk from Repo
        shell: pwsh
        run: |
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          
          # CHANGE THIS to your raw file URL:
          $RustDeskUrl = "https://raw.githubusercontent.com/zafarsadikk/tester/main/rustdesk-1.3.8-x86_64.exe"

          Write-Host "Downloading RustDesk EXE from your repo..."
          Invoke-WebRequest -Uri $RustDeskUrl -OutFile "$env:TEMP\rustdesk.exe" -UseBasicParsing -Headers @{ 'User-Agent' = 'Mozilla/5.0' }

          Write-Host "Creating RustDesk config folder..."
          New-Item -ItemType Directory -Path "$env:APPDATA\RustDesk" -Force | Out-Null

          Write-Host "Starting RustDesk..."
          # If RustDesk has a silent mode, use "/S" or similar. Otherwise just start it:
          Start-Process -FilePath "$env:TEMP\rustdesk.exe"

      - name: Fetch RustDesk ID
        shell: pwsh
        run: |
          Write-Host "Waiting 15s for RustDesk to generate the ID..."
          Start-Sleep -Seconds 15
          $IDPath = "$env:APPDATA\RustDesk\id"
          if (Test-Path $IDPath) {
            $ID = Get-Content $IDPath
            Write-Host "RustDesk ID: $ID"
          } else {
            Write-Host "Could not find RustDesk ID at $IDPath."
          }

      - name: Keep Runner Alive for 30 Minutes
        shell: pwsh
        run: Start-Sleep -Seconds 1800
