name: Setup Windows Runner with Python and RustDesk

on:
  workflow_dispatch:

jobs:
  setup-windows:
    runs-on: windows-latest
    steps:
      - name: Install Python 3.10
        shell: pwsh
        run: |
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.10.11/python-3.10.11-amd64.exe" -OutFile "$env:TEMP\python-installer.exe" -UseBasicParsing
          Start-Process -FilePath "$env:TEMP\python-installer.exe" -ArgumentList "/quiet InstallAllUsers=1 PrependPath=1" -Wait
          Write-Host "Python version:"
          python --version

      - name: Install RustDesk (Portable)
        shell: pwsh
        run: |
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          # Direct link to RustDesk 1.3.8 (64-bit) portable ZIP from the "Assets" section
          $RustDeskUrl        = "https://github.com/rustdesk/rustdesk/releases/download/1.3.8/rustdesk-1.3.8-x86_64-pc-windows-msvc.zip"
          $RustDeskZip        = "$env:TEMP\rustdesk.zip"
          $RustDeskExtract    = "$env:TEMP\rustdesk"

          Write-Host "Using RustDesk download link: $RustDeskUrl"

          # Download the ZIP file with a user agent so GitHub doesn’t return HTML
          Invoke-WebRequest -Uri $RustDeskUrl -OutFile $RustDeskZip -Headers @{ 'User-Agent' = 'Mozilla/5.0' }

          Write-Host "Extracting RustDesk..."
          Expand-Archive -Path $RustDeskZip -DestinationPath $RustDeskExtract -Force

          # Ensure RustDesk can write its ID file
          New-Item -ItemType Directory -Path "$env:APPDATA\RustDesk" -Force | Out-Null

          Write-Host "Starting RustDesk..."
          Start-Process -FilePath "$RustDeskExtract\rustdesk.exe"

      - name: Fetch RustDesk ID
        shell: pwsh
        run: |
          Write-Host "Waiting 20s for RustDesk to generate the ID..."
          Start-Sleep -Seconds 20
          $RustDeskIDPath = "$env:APPDATA\RustDesk\id"
          if (Test-Path $RustDeskIDPath) {
            $RustDeskID = Get-Content $RustDeskIDPath
            Write-Host "🚀 RustDesk ID: $RustDeskID"
          } else {
            Write-Host "⚠️ RustDesk ID not found at $RustDeskIDPath. Check manually."
          }

      # Optional: keep the runner alive for 30 minutes so you can connect
      - name: Keep Runner Alive for 30 Minutes
        shell: pwsh
        run: Start-Sleep -Seconds 1800
